# Global scaling factor (1.0 = no scaling)
scaling = 1.0

# G2 symmetry functions (radial symmetry)
# Format: eta (Å^-2), rcutoff (Å), rshift (Å), Normalization Factor
G2 = [
    # eta  rcutoff  rshift  norm
    # G2(eta=0, rshift=0) - Local Density
    # [0.000, 14.00, 0.00, 1.00],
    # G2(eta=0, rshift=0) R_cutoff = 5.5 Å - Repulsion Region
    [0.000, 5.50, 0.00, 1.00],
    # Grid with Resolution eta = 4 and Step - 0.4 Å
    [16.00, 14.0, 3.00, 1.00],
    [16.00, 14.0, 3.20, 1.00],
    [16.00, 14.0, 3.40, 1.00],
    [16.00, 14.0, 3.60, 1.00],
    [16.00, 14.0, 3.80, 1.00],
    [16.00, 14.0, 4.00, 1.00],
    [16.00, 14.0, 4.20, 1.00],
    [16.00, 14.0, 4.40, 1.00],
    [16.00, 14.0, 4.60, 1.00],
    [16.00, 14.0, 4.80, 1.00],
    [16.00, 14.0, 5.00, 1.00],
    [16.00, 14.0, 5.20, 1.00],
    [16.00, 14.0, 5.40, 1.00],
    [16.00, 14.0, 5.60, 1.00],
    [16.00, 14.0, 5.80, 1.00],
    [16.00, 14.0, 6.00, 1.00],
]

# G3 symmetry functions (narrow angular symmetry)
# Format: eta (Å^-2), lambda (+1/-1), zeta, rcutoff (Å), rshift (Å)
# G3 = [
#     # eta  lambda  zeta  rcutoff  rshift
#     [0.001,  1.0, 1.0, 5.0, 0.0],
#     [0.001, -1.0, 1.0, 5.0, 0.0],
# ]

# G9 symmetry functions (wide angular symmetry)
# Format: eta (Å^-2), lambda (+1/-1), zeta, rcutoff (Å), rshift (Å)
# G9 = [
#     # eta  lambda  zeta  rcutoff  rshift
#     [0.001,  1.0, 1.0, 5.0, 0.0],
#     [0.001, -1.0, 1.0, 5.0, 0.0],
# ]
